---
version: '3.4'
services:

  validator1:
    build:
      context: quorum
      args:
        QUORUM_VERSION: ${QUORUM_VERSION}
    image: sample-network/quorum:${QUORUM_VERSION}
    ports:
      - "22000:8545"
    environment:
      - NODE_ID=1
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    entrypoint: >
      /bin/sh -c
      "
      mv /quorum /data;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth --datadir=/data init /config/genesis.json;

      geth
      --identity node${NODE_ID}-${QUORUM_CONS_ALGO:-istanbul}
      --config=/config/config.toml
      --rpcapi admin,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONS_ALGO:-istanbul}
      --password /config/passwords.txt
      --verbosity=5 --unlock 0 --emitcheckpoints --mine --minerthreads 1"
    volumes:
      - ./config/quorum/config.toml:/config/config.toml
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./logs/geth:/var/log/
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/networkFiles/validator1:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.11

  validator2:
    image: sample-network/quorum:${QUORUM_VERSION}
    ports:
      - "22001:8545"
    environment:
      - NODE_ID=2
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    entrypoint: >
      /bin/sh -c
      "
      mv /quorum /data;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth --datadir=/data init /config/genesis.json;

      geth
      --identity node${NODE_ID}-${QUORUM_CONS_ALGO:-istanbul}
      --config=/config/config.toml
      --rpcapi admin,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONS_ALGO:-istanbul}
      --password /config/passwords.txt
      --verbosity=5 --unlock 0 --emitcheckpoints --mine --minerthreads 1"
    volumes:
      - ./config/quorum/config.toml:/config/config.toml
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./logs/geth:/var/log/
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/networkFiles/validator2:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.12

  validator3:
    image: sample-network/quorum:${QUORUM_VERSION}
    ports:
      - "22002:8545"
    environment:
      - NODE_ID=3
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    entrypoint: >
      /bin/sh -c
      "
      mv /quorum /data;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth --datadir=/data init /config/genesis.json;

      geth
      --identity node${NODE_ID}-${QUORUM_CONS_ALGO:-istanbul}
      --config=/config/config.toml
      --rpcapi admin,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONS_ALGO:-istanbul}
      --password /config/passwords.txt
      --verbosity=5 --unlock 0 --emitcheckpoints --mine --minerthreads 1"
    volumes:
      - ./config/quorum/config.toml:/config/config.toml
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./logs/geth:/var/log/
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/networkFiles/validator3:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.13

  validator4:
    image: sample-network/quorum:${QUORUM_VERSION}
    ports:
      - "22003:8545"
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    entrypoint: >
      /bin/sh -c
      "
      mv /quorum /data;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth --datadir=/data init /config/genesis.json;

      geth
      --identity node${NODE_ID}-${QUORUM_CONS_ALGO:-istanbul}
      --config=/config/config.toml
      --rpcapi admin,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONS_ALGO:-istanbul}
      --password /config/passwords.txt
      --verbosity=5 --unlock 0 --emitcheckpoints --mine --minerthreads 1"
    volumes:
      - ./config/quorum/config.toml:/config/config.toml
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./logs/geth:/var/log/
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/networkFiles/validator4:/config/keys
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.14

  rpcnode:
    image: sample-network/quorum:${QUORUM_VERSION}
    ports:
      - "22004:8545"
    environment:
      - NODE_ID=5
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    entrypoint: >
      /bin/sh -c
      "
      mv /quorum /data;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth --datadir=/data init /config/genesis.json;

      geth
      --identity node${NODE_ID}-${QUORUM_CONS_ALGO:-istanbul}
      --config=/config/config.toml
      --rpcapi admin,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONS_ALGO:-istanbul}
      --password /config/passwords.txt
      --verbosity=5 --unlock 0 --emitcheckpoints"
    volumes:
      - ./config/quorum/config.toml:/config/config.toml
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./logs/geth:/var/log/
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/networkFiles/rpcnode:/config/keys

#  cakeshop:
#    << : *cakeshop-def
#    hostname: cakeshop
#    ports:
#      - "8999:8999"
#    volumes:
#      - cakeshopvol:/qdata
#      - ./examples/7nodes:/examples:ro
#    networks:
#      quorum-examples-net:
#        ipv4_address: 172.16.239.186

  explorer:
    build: block-explorer-light
    image: sample-network/block-explorer-light:${BESU_VERSION}
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.20

networks:
  quorum-examples-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  "vol1":
  "vol2":
  "vol3":
  "vol4":
  "vol5":
  "vol6":
  "vol7":
  "cakeshopvol":
