- kind: HashicorpSecrets
  name: hashicorp-secrets
  specs:
    mountPoint: quorum
    address: http://vault:8200
    token: "DevVaultToken"
    namespace: ''
- kind: HashicorpKeys
  name: hashicorp-keys
  specs:
    mountPoint: quorum
    address: http://vault:8200
    token: "DevVaultToken"
    namespace: ''
- kind: LocalKeys
  name: local-keys
  specs:
    secretstore: HashicorpSecrets
    specs:
      mountPoint: quorum
      address: http://vault:8200
      token: "DevVaultToken"
      namespace: ''
- kind: Ethereum
  name: eth-accounts
  specs:
    keystore: HashicorpKeys
    specs:
      mountPoint: quorum
      address: http://vault:8200
      token: "DevVaultToken"
      namespace: ''
