- kind: HashicorpSecrets
  name: hashicorp-secrets
  specs:
    mountPoint: quorum
    address: http://vault:8200
    token: "DevVaultToken"
    namespace: ''
- kind: HashicorpKeys
  name: hashicorp-keys
  specs:
    mountPoint: quorum
    address: http://vault:8200
    token: "DevVaultToken"
    namespace: ''
- kind: LocalKeys
  name: local-keys
  specs:
    secretstore: HashicorpSecrets
    specs:
      mountPoint: quorum
      address: http://vault:8200
      token: "DevVaultToken"
      namespace: ''
- kind: Ethereum
  name: eth-accounts
  specs:
    keystore: HashicorpKeys
    specs:
      mountPoint: quorum
      address: http://vault:8200
      token: "DevVaultToken"
      namespace: ''
{% if clientType == "goquorum" %}
- kind: Node
  name: quorum-node
  specs:
    rpc:
      addr: http://network_member1quorum_1:8545
    tessera:
      addr: http://network_member1tessera_1:9080
{% else %}
- kind: Node
  name: besu-node
  specs:
    rpc:
      addr: http://network_member1besu_1:8545
{% endif %}
